services:
  tx-validator:
    hostname: tx-validator
    image: j9r/tx-validator
    container_name: tx-validator
    ports:
      - 8000:8000
  sqs-local:
    image: localstack/localstack
    container_name: sqs-local
    hostname: sqs-local
    ports:
      - 4566:4566
    environment:
      - SERVICES=sqs
      - TART_WEB=0
    volumes:
      - ./volume:/var/lib/localstack
  tx-producer:
    hostname: tx-producer
    image: j9r/tx-producer
    container_name: tx-producer
    ports:
      - 8082:8080
    environment:
      - QUARKUS_SQS_ENDPOINT_OVERRIDE=http://sqs-local:4566
  tx-consumer:
    hostname: tx-consumer
    image: j9r/tx-consumer
    container_name: tx-consumer
    ports:
      - 8081:8081
    environment:
      - QUARKUS_SQS_ENDPOINT_OVERRIDE=http://sqs-local:4566
      - QUARKUS_REST_CLIENT_VALIDATION_API_URL=http://tx-validator:8000
      - QUARKUS_SQS_API_CALL_TIMEOUT=3600